dist: xenial
language: ruby

services:
  - docker

env:
  global:
    - LOCAL_BIN=${HOME}/.local/bin # For downloaded tools like terraform and awscli
    # Retrieve commit tag values for each micro-service folder to be used in tagging and deploying docker images.
    # Dependency folders are included as well and must be maintained
    - REA_APP_TAG=$(git log --pretty=format:rc-%h -n 1 -- app)
    - TESTBOX_TAG=$(git log --pretty=format:rc-%h -n 1 -- app)

before_install:
  - mkdir -p ${LOCAL_BIN}
  - export PATH=${PATH}:${LOCAL_BIN}    # Put aws in the path
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - make common-deps                    # install dependencies from Makefile in the root

script:
  - set -e               # Stop script immediately on error
  - cd $SERVICE_DIR
  - export AWS_PROFILE=${TARGET_AWS_PROFILE}
  - make check-image-exists && travis_terminate 0 || echo "Image doesn't exist, continue with build process";
  - make publish         # Publish will do the build

# This governs the order of stage-execution
stages:
  - name: build
  - name: deployment

jobs:
  include:
    - stage: build
      name: "‚úçÔ∏è REA WEB SERVER: Build, test and publish the image"
      env:
        - SERVICE_DIR=app
        - TARGET_AWS_PROFILE=AWS_STEVE
        - COMMIT_HASH=${REA_APP_TAG}
      if: (branch = tag AND tag =~ /v\d+.\d+(.\d+)?/) OR (branch != tag)
    
    - stage: build
      name: "‚úçÔ∏è TESTBOX: Build, test and publish the image"
      env:
        - SERVICE_DIR=testbox
        - TARGET_AWS_PROFILE=AWS_STEVE
        - COMMIT_HASH=${TESTBOX_TAG}
      if: (branch = tag AND tag =~ /v\d+.\d+(.\d+)?/) OR (branch != tag)

    # Deploy the infrastructure
    - stage: deployment
      name: "üèñÔ∏è Branch manual deploy to AWS: Apply changes to kubernetes infrastructure and update container images"
      env:
        - SERVICE_DIR=infra
        - REGION=ap-southeast-2
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      script:
        - set -e # Stop script immediately on error
        - cd $SERVICE_DIR
        - make depend
        - make deploy
      if: commit_message ="deploy-to-aws" AND type != pull_request

    - stage: deployment
      name: "‚ô®Ô∏è Branch manual destroy AWS: Destroy changes in aws"
      env:
        - SERVICE_DIR=infra
        - REGION=ap-southeast-2
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      script:
        - set -e # Stop script immediately on error
        - cd $SERVICE_DIR
        - make depend
        - make destroy-terraform
      if: commit_message ="destroy-to-aws" AND type != pull_request